export const STOCK_ADJUSTMENT_ERROR_CODES = {
  NOT_FOUND: "STOCK_ADJUSTMENT_NOT_FOUND",
  PRODUCT_NOT_FOUND: "STOCK_ADJUSTMENT_PRODUCT_NOT_FOUND",
  INVALID_QUANTITY: "STOCK_ADJUSTMENT_INVALID_QUANTITY",
  CANNOT_DELETE: "STOCK_ADJUSTMENT_CANNOT_DELETE",
} as const;
