/**
 * Authentication module constants — no runtime logic.
 */

export const AUTH_ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_REUSE: "REFRESH_TOKEN_REUSE",
  FORBIDDEN: "FORBIDDEN",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  VERIFICATION_TOKEN_INVALID: "VERIFICATION_TOKEN_INVALID",
  VERIFICATION_OTP_INVALID: "VERIFICATION_OTP_INVALID",
  VERIFICATION_OTP_EXPIRED: "VERIFICATION_OTP_EXPIRED",
  VERIFICATION_OTP_MAX_ATTEMPTS: "VERIFICATION_OTP_MAX_ATTEMPTS",
  VERIFICATION_RESEND_COOLDOWN: "VERIFICATION_RESEND_COOLDOWN",
  LOGIN_OTP_INVALID: "LOGIN_OTP_INVALID",
  LOGIN_OTP_EXPIRED: "LOGIN_OTP_EXPIRED",
  LOGIN_OTP_MAX_ATTEMPTS: "LOGIN_OTP_MAX_ATTEMPTS",
  LOGIN_OTP_RESEND_COOLDOWN: "LOGIN_OTP_RESEND_COOLDOWN",
  LOGIN_OTP_PHONE_REQUIRED: "LOGIN_OTP_PHONE_REQUIRED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

export const AUTH_COOKIE_NAMES = {
  REFRESH_TOKEN: "salon_refresh_token",
} as const;

export const AUTH_HEADERS = {
  AUTHORIZATION: "Authorization",
} as const;

export const AUTH_TOKEN_PREFIXES = {
  BEARER: "Bearer",
} as const;

export const JWT_PAYLOAD_VERSION = 1;

export const AUTH_TOKEN_TYPES = {
  BEARER: "Bearer",
} as const;
