import { Router } from "express";
import { appointmentsRouter } from "../modules/appointments/appointments.routes";
import { advancesRouter } from "../modules/advances/advances.routes";
import { accountingRouter } from "../modules/accounting/accounting.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { billingRouter } from "../modules/billing/billing.routes";
import { couponsRouter } from "../modules/coupons/coupons.routes";
import { customersRouter } from "../modules/customers/customers.routes";
import { appNotificationsRouter } from "../modules/app-notifications/app-notifications.routes";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes";
import { membershipTiersRouter } from "../modules/membership-tiers/membership-tiers.routes";
import { plansRouter } from "../modules/plans/plans.routes";
import { productCategoriesRouter } from "../modules/product-categories/product-categories.routes";
import { productsRouter } from "../modules/products/products.routes";
import { searchRouter } from "../modules/search/search.routes";
import { serviceCategoriesRouter } from "../modules/service-categories/service-categories.routes";
import { serviceProductLinksRouter } from "../modules/service-product-links/service-product-links.routes";
import { servicesRouter } from "../modules/services/services.routes";
import { settingsRouter } from "../modules/settings/settings.routes";
import { staffRouter } from "../modules/staff/staff.routes";
import { uploadsRouter } from "../modules/uploads/uploads.routes";
import { feedbackRouter } from "../modules/feedback/feedback.routes";
import { inventoryRouter } from "../modules/inventory/inventory.routes";
import { stockAdjustmentsRouter } from "../modules/stock-adjustments/stock-adjustments.routes";
import { stockPurchasesRouter } from "../modules/stock-purchases/stock-purchases.routes";
import { vendorsRouter } from "../modules/vendors/vendors.routes";
import { franchisesRouter } from "../modules/franchises/franchises.routes";
import { myFranchiseRouter } from "../modules/my-franchise/my-franchise.routes";
import healthRoutes from "./healthRoutes";

const apiRouter = Router();

apiRouter.use(healthRoutes);
apiRouter.use("/auth", authRouter);
apiRouter.use("/franchises", franchisesRouter);
apiRouter.use("/my-franchise", myFranchiseRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/notifications", appNotificationsRouter);
apiRouter.use("/appointments", appointmentsRouter);
apiRouter.use("/services", servicesRouter);
apiRouter.use("/service-categories", serviceCategoriesRouter);
apiRouter.use("/product-categories", productCategoriesRouter);
apiRouter.use("/products", productsRouter);
apiRouter.use("/vendors", vendorsRouter);
apiRouter.use("/stock-purchases", stockPurchasesRouter);
apiRouter.use("/stock-adjustments", stockAdjustmentsRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/billing", billingRouter);
apiRouter.use("/feedback", feedbackRouter);
apiRouter.use("/plans", plansRouter);
apiRouter.use("/coupons", couponsRouter);
apiRouter.use("/membership-tiers", membershipTiersRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/staff", staffRouter);
apiRouter.use("/uploads", uploadsRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/advances", advancesRouter);
apiRouter.use("/accounting", accountingRouter);
apiRouter.use("/service-product-links", serviceProductLinksRouter);

export { apiRouter };
