export const PRODUCT_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
} as const;

export const PRODUCT_ERROR_CODES = {
  NOT_FOUND: "PRODUCT_NOT_FOUND",
  DUPLICATE_NAME: "PRODUCT_DUPLICATE_NAME",
  DUPLICATE_SKU: "PRODUCT_DUPLICATE_SKU",
  DUPLICATE_BARCODE: "PRODUCT_DUPLICATE_BARCODE",
  CATEGORY_NOT_FOUND: "PRODUCT_CATEGORY_NOT_FOUND",
  VENDOR_NOT_FOUND: "PRODUCT_VENDOR_NOT_FOUND",
  HAS_TRANSACTIONS: "PRODUCT_HAS_TRANSACTIONS",
} as const;
