export const STOCK_PURCHASE_ERROR_CODES = {
  NOT_FOUND: "STOCK_PURCHASE_NOT_FOUND",
  VENDOR_NOT_FOUND: "STOCK_PURCHASE_VENDOR_NOT_FOUND",
  PRODUCT_NOT_FOUND: "STOCK_PURCHASE_PRODUCT_NOT_FOUND",
  CANNOT_DELETE: "STOCK_PURCHASE_CANNOT_DELETE",
} as const;
