export const PRODUCT_CATEGORY_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
} as const;

export const PRODUCT_CATEGORY_ERROR_CODES = {
  NOT_FOUND: "PRODUCT_CATEGORY_NOT_FOUND",
  DUPLICATE_NAME: "PRODUCT_CATEGORY_DUPLICATE_NAME",
  HAS_PRODUCTS: "PRODUCT_CATEGORY_HAS_PRODUCTS",
} as const;
