export const SERVICE_CATEGORY_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
} as const;

export const SERVICE_CATEGORY_ERROR_CODES = {
  NOT_FOUND: "SERVICE_CATEGORY_NOT_FOUND",
  DUPLICATE_NAME: "SERVICE_CATEGORY_DUPLICATE_NAME",
  HAS_SERVICES: "SERVICE_CATEGORY_HAS_SERVICES",
} as const;
